services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NEXT_PUBLIC_LIFF_ID=${NEXT_PUBLIC_LIFF_ID}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - NODE_ENV=${NODE_ENV:-development}
    networks:
      - liff-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http app:3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - app
    networks:
      - liff-network

networks:
  liff-network:
    driver: bridge
