export type FormDataType = {
  purchase_date?: string;
  total_price?: number;
  land_price?: number;
  building_price?: number;
  purchase_expenses?: number;
  building_age?: number;
  structure?: string;
  gross_yield?: number;
  current_yield?: number;
  full_occupancy_rental_income?: number;
  vacancy_rate?: number;
  rent_decline_rate?: number;
  annual_operating_expenses?: number;
  own_capital?: number;
  loan_amount?: number;
  loan_term_years?: number;
  interest_rate?: number;
  loan_type?: string;
  expected_rate_of_return?: number;
  expected_sale_year?: string;
  expected_sale_price?: number;
  sale_expenses?: number;
  owner_type?: string;
  annual_income?: number;
};
